// A browser's toolbar across the top of every page — a tab, back / forward /
// reload and an address bar — so the fake web reads like the real one: the
// bar shows https://crumbforum.net/threads/starter-smells, not Foogle's
// /web/crumbforum.net/threads/starter-smells, and Foogle's own pages show
// https://www.foogle.com/search?q=….
//
// The bar is the first thing in a response, so it is on screen before a
// page's first generated byte. It is drawn inside a declarative shadow root,
// where no site's styles can reach it, and public/fw/browserbar.js makes it
// work. The address field is a plain GET form to /go, which works before
// that script arrives. FOOGLE_BROWSER_BAR=0 turns the whole thing off.

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { Router } from "express";
import { siteMark } from "./icons.js";
import { siteLook } from "./pages.js";

export const FOOGLE_HOST = "www.foogle.com";
export const barEnabled = () => process.env.FOOGLE_BROWSER_BAR !== "0";

const esc = (s) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

// ---------- request URL -> the URL a real browser would show ----------
// Foogle's context on a result link (see webHref in server.js); not part of
// the site's own URL.
const CONTEXT = new Set(["fq", "ft", "fs", "fk"]);
const paramName = (pair) => {
  try { return decodeURIComponent(pair.split("=")[0].replace(/\+/g, " ")); } catch { return pair; }
};

// Percent-escaped UTF-8 is shown as the characters it spells, as address
// bars do; escaped ASCII (%20, %2F, %26) stays escaped, so the URL still
// means the same thing when copied.
const readable = (s) => s.replace(/(?:%[89a-f][\da-f])+/gi, (run) => {
  try { return decodeURIComponent(run); } catch { return run; }
});

// "/web/crumbforum.net/threads/x?fq=…" -> { host: "crumbforum.net", path: "/threads/x", site: true }
// "/search?q=bread" -> { host: "www.foogle.com", path: "/search?q=bread", site: false }
export function addressOf(requestUrl) {
  const raw = String(requestUrl || "/");
  const at = raw.indexOf("?");
  const pathname = at === -1 ? raw : raw.slice(0, at);
  let search = at === -1 ? "" : raw.slice(at + 1);
  const web = pathname.match(/^\/web\/([^/]+)(\/.*)?$/);
  if (!web) return { host: FOOGLE_HOST, path: readable(`${pathname}${search ? `?${search}` : ""}`), site: false };
  search = search.split("&").filter((p) => p && !CONTEXT.has(paramName(p))).join("&");
  return { host: readable(web[1]).toLowerCase(), path: readable(`${web[2] || "/"}${search ? `?${search}` : ""}`), site: true };
}

export const displayURL = (requestUrl) => {
  const { host, path } = addressOf(requestUrl);
  return `https://${host}${path}`;
};

// ---------- what typing in the address bar does ----------
// Like a real omnibox: something shaped like a URL goes to that site (on the
// fake web), anything else is a Foogle search. Always returns a path on
// Foogle's own origin, never an absolute or protocol-relative URL.
const LABEL = /^(?!-)[\p{L}\p{N}-]{1,63}(?<!-)$/u;
const TLD = /^(?:\p{L}{2,63}|xn--[a-z\d-]{1,59})$/iu;
// "node.js" and "notes.txt" are file names people search for, not sites.
const FILE_TYPES = new Set(("js mjs cjs ts tsx jsx py rb go rs java kt swift c h cpp cs php sh bat ps1 json yml yaml toml xml ini " +
  "md txt csv log html htm css scss pdf doc docx xls xlsx ppt pptx png jpg jpeg gif svg webp heic mp3 wav mp4 mov avi mkv zip tar gz exe dmg apk iso").split(" "));

function looksLikeHost(host) {
  const name = host.replace(/:\d{1,5}$/, "").toLowerCase();
  if (name === "localhost" || /^\d{1,3}(?:\.\d{1,3}){3}$/.test(name) || /^\[[\da-f:.]+\]$/.test(name)) return true;
  const labels = name.split(".");
  return labels.length > 1 && labels.every((l) => LABEL.test(l)) && TLD.test(labels.at(-1));
}

// `here` is the Host Foogle is being browsed on (localhost:3000, a LAN
// address): a pasted Foogle link stays on Foogle.
export function omniboxTarget(input, { here = "" } = {}) {
  const text = String(input ?? "").trim();
  const search = (q) => (q ? `/search?${new URLSearchParams({ q })}` : "/");
  if (!text) return "/";
  if (text.startsWith("?")) return search(text.slice(1).trim()); // "?term" forces a search
  if (/^\/(?![/\\])[^\s\\]*$/.test(text)) return text; // a path on Foogle itself
  const scheme = text.match(/^([a-z][a-z\d+.-]*):\/\//i)?.[1].toLowerCase();
  if (scheme && scheme !== "http" && scheme !== "https") return search(text);
  const rest = scheme ? text.slice(scheme.length + 3) : text;
  const host = rest.split(/[/?#]/)[0];
  if (!scheme) {
    if (/\s/.test(text) || host.includes("@") || !looksLikeHost(host)) return search(text);
    const labels = host.split(".");
    if (host === rest && labels.length === 2 && FILE_TYPES.has(labels[1].toLowerCase())) return search(text);
  }
  let url;
  try { url = new URL(`https://${rest}`); } catch { return search(text); }
  if (!url.hostname) return search(text);
  const pathname = url.pathname.replace(/^\/+/, "/");
  const tail = `${url.search}${url.hash}`;
  if (url.host === String(here).toLowerCase() || /^(?:www\.)?foogle\.com$/.test(url.hostname)) return `${pathname}${tail}`;
  return `/web/${url.host}${pathname === "/" ? "" : pathname}${tail}`;
}

// ---------- the tab ----------
const FOOGLE_TABS = { "/search": "Search", "/images": "Images", "/news": "News", "/maps": "Maps", "/timelines": "Timelines" };

// What the tab says until the page's own <title> arrives (the script swaps
// it in): the result title the visitor clicked, or the URL, as a browser
// shows while a page loads.
export function tabTitle(requestUrl) {
  const u = new URL(String(requestUrl || "/"), "http://foogle.invalid");
  const { host, path, site } = addressOf(requestUrl);
  if (site) return u.searchParams.get("ft") || `${host}${path === "/" ? "" : path}`;
  const q = u.searchParams.get("q");
  return q && FOOGLE_TABS[u.pathname] ? `${q} - Foogle ${FOOGLE_TABS[u.pathname]}` : "Foogle";
}

const svgImage = (svg) =>
  `data:image/svg+xml,${encodeURIComponent(svg.replace(/^<svg /, '<svg xmlns="http://www.w3.org/2000/svg" '))}`;
const FOOGLE_ICON = svgImage(`<svg viewBox="0 0 16 16"><rect width="16" height="16" rx="4" fill="#fff"/><path fill="#4285f4" d="M4 2h3v12H4z"/><path fill="#ea4335" d="M4 2h8.5v3H4z"/><path fill="#fbbc05" d="M7 7h4.5v3H7z"/><path fill="#34a853" d="M4 12h3v2H4z"/></svg>`);

// A site's favicon is its logo mark (lib/icons.js), the one its search result
// and its own header show. Once the site has a look, that fixes the mark;
// before, the result kind the visitor clicked usually does, and the script
// takes the mark from the page's header when it arrives.
function favicon({ host, site }, kind) {
  if (!site) return FOOGLE_ICON;
  const domain = host.replace(/:\d+$/, "");
  const look = siteLook(domain);
  return svgImage(siteMark(domain, look ? { kind: look.mark || look.kind, hue: look.hue } : { kind }));
}

// ---------- markup ----------
const icon = (d, cls = "") => `<svg${cls ? ` class="${cls}"` : ""} viewBox="0 0 24 24" aria-hidden="true"><path d="${d}"/></svg>`;
const ICONS = {
  back: icon("M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z"),
  forward: icon("M12 4l-1.41 1.41L16.17 11H4v2h12.17l-5.58 5.59L12 20l8-8z"),
  reload: icon("M17.65 6.35A7.96 7.96 0 0 0 12 4a8 8 0 1 0 7.73 10h-2.08A6 6 0 1 1 12 6c1.66 0 3.14.69 4.22 1.78L13 11h7V4l-2.35 2.35z", "go"),
  stop: icon("M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z", "stop"),
  lock: icon("M18 8h-1V6A5 5 0 0 0 7 6v2H6a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V10a2 2 0 0 0-2-2zM9 6a3 3 0 0 1 6 0v2H9V6zm3 11a2 2 0 1 1 0-4 2 2 0 0 1 0 4z"),
  close: icon("M18.3 5.71 16.89 4.3 12 9.17 7.11 4.3 5.7 5.71 10.59 10.6 5.7 15.49l1.41 1.41L12 12.01l4.89 4.89 1.41-1.41-4.89-4.89z"),
  plus: icon("M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"),
};

// The address, split so the host can stand out (and stand alone on a phone).
function addressParts({ host, path }) {
  const www = host.startsWith("www.") ? "www." : "";
  return `<span class="s">https://</span><span class="w">${www}</span><span class="h">${esc(host.slice(www.length))}</span><span class="p" data-path="${esc(path)}">${path === "/" ? "" : esc(path)}</span>`;
}

const asset = (file) => readFileSync(new URL(`../public/fw/${file}`, import.meta.url), "utf8");
// Inlined rather than linked, so the bar is styled in the same bytes that
// draw it. Comments and runs of whitespace aren't worth sending on every page.
const BAR_CSS = asset("browserbar.css").replace(/\/\*[\s\S]*?\*\//g, "").replace(/\s+/g, " ").trim();
const version = createHash("sha1").update(asset("browserbar.js")).digest("hex").slice(0, 8);

// The page scrolls inside <body>, which starts below the bar: a site's
// sticky header then sticks under the bar rather than behind it, and nothing
// on the page is ever covered. The heights match public/fw/browserbar.css.
// Modal dialogs and their backdrops, Foogle's loading line and the cart
// drawer (widgets.css) sit below the bar too, as they would in a browser; a
// sidebar header (lib/theme.js) fits the shorter viewport.
const FRAME_CSS = `:root{--fbar-h:75px}@media (max-width:640px),(max-height:480px){:root{--fbar-h:49px}}
@media screen{html{overflow:hidden!important}body{position:fixed!important;inset:var(--fbar-h) 0 0 0!important;height:auto!important;min-height:0!important;max-height:none!important;overflow:auto!important;scroll-behavior:inherit}
#__fvb,dialog:modal,::backdrop{top:var(--fbar-h)!important}dialog.fw-drawer{height:auto!important;max-height:none!important}header.site.side{height:calc(100vh - var(--fbar-h))!important}}`;

// The first bytes of a page. It opens the document; the page's own
// <!DOCTYPE>/<html>/<head> follow in body context, which HTML parsers merge
// (see vibePrelude in server.js). No <title> here: the page's own must be the
// document's first. `loading` is for a page that streams in.
export function browserBar(req, { loading = false } = {}) {
  if (!barEnabled()) return "";
  const requestUrl = req.originalUrl ?? req.url;
  const address = addressOf(requestUrl);
  const url = `https://${address.host}${address.path}`;
  const title = tabTitle(requestUrl);
  const kind = address.site ? new URL(requestUrl, "http://foogle.invalid").searchParams.get("fk") : null;
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${FRAME_CSS}</style></head><body>
<foogle-bar${loading ? " loading" : ""}${address.site ? " data-site" : ""}><template shadowrootmode="open"><style>${BAR_CSS}</style>
<div class="tabs"><div class="tab" title="${esc(title)}"><span class="ico"><img class="fav" src="${esc(favicon(address, kind))}" alt=""><i class="spin"></i></span><span class="title">${esc(title)}</span><a class="x" href="/" aria-label="Close tab" title="Close tab">${ICONS.close}</a></div><a class="new" href="/" target="_blank" aria-label="New tab" title="New tab">${ICONS.plus}</a></div>
<div class="tool"><button class="btn back" type="button" aria-label="Back" title="Back">${ICONS.back}</button><button class="btn fwd" type="button" aria-label="Forward" title="Forward">${ICONS.forward}</button><button class="btn reload" type="button" aria-label="Reload" title="Reload this page">${ICONS.reload}${ICONS.stop}</button>
<form class="omni" action="/go" method="get"><button class="lock" type="button" popovertarget="site-info" aria-label="View site information" title="View site information">${ICONS.lock}</button><label class="field"><input name="q" value="${esc(url)}" aria-label="Address and search bar" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" enterkeyhint="go"><span class="url" aria-hidden="true">${addressParts(address)}</span></label></form></div>
<div class="pop" id="site-info" popover><div class="pop-h">${ICONS.lock}<b>Connection is secure</b></div><p>Your information (for example, passwords or credit card numbers) is private when it is sent to this site.</p><p class="cert">Certificate issued to <b>${esc(address.host)}</b> by Foogle Trust Services · valid until 2089</p></div>
</template></foogle-bar><script src="/fw/browserbar.js?v=${version}" async></script>
`;
}

// ---------- routes ----------
// /go is the address bar's form. The homepage is a static file, so it gets
// its bar here; with the bar off it is served as before.
export function browserBarRoutes() {
  const router = Router();
  const home = readFileSync(new URL("../public/index.html", import.meta.url), "utf8");
  router.get("/go", (req, res) => {
    const q = [].concat(req.query.q ?? "")[0];
    res.redirect(omniboxTarget(q, { here: req.headers.host }));
  });
  router.get("/", (req, res, next) => {
    if (!barEnabled()) return next();
    res.type("html").send(browserBar(req) + home);
  });
  return router;
}
